site_name: BRV
site_author: drake
site_description: BRV框架文档
copyright: Copyright &copy; 2018 - 2020 劉強東

repo_name: GitHub
repo_url: https://github.com/liangjingkanji/BRV

extra_css:
  - css/extra.css

docs_dir: 'docs'

theme:
  name: material
  custom_dir: docs/material

  palette:
    scheme: drake
    primary: white

  font: false

  language: zh

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed

nav:
  - 使用: index.md
  - 多类型: multi-type.md
  - 更新数据: refresh-data.md
  - 点击事件: click.md
  - 生命周期: lifecycle.md
  - 滑动卡顿: performance.md
  - 头脚布局: header_footer.md
  - 分组: group.md
  - 悬停: hover.md
  - 分割线:
      - 线性列表: divider-linear.md
      - 网格列表: divider-grid.md
      - 瀑布流列表: divider-staggerd.md
      - 自定义: divider-other.md
  - 缺省页: state.md
  - 下拉刷新/上拉加载: refresh.md
  - 拉取更多: upfetch.md
  - 预加载/预拉取: preload.md
  - 切换模式: toggle.md
  - 选择模式: checked.md
  - 伸缩布局: flexbox.md
  - 拖拽: drag.md
  - 侧滑: swipe.md
  - 列表动画: animation.md
  - 数据接口: item.md
  - 复用列表: recycle.md
  - 扩展函数: extension.md
  - 网络请求: net.md
  - ViewBinding: view-binding.md
  - 常见问题: https://github.com/liangjingkanji/BRV/blob/master/docs/issues.md
  - 第三方组件: component.md
  - 更新日志: updates.md
  - 1.x文档: api/index.html